//! Golden-vector parity with the Node PoC (CC-030, DR-PF-01).
//!
//! Reads `qa/golden/crypto/vectors.json` (generated by
//! `poc/tools/gen-golden.js`) and asserts the Rust field/encoding/sharing math
//! produces byte-identical results. A tiny std-only JSON reader avoids adding
//! a dependency to the zero-dep crate's test surface.

use pocketcloud_crypto::encoding::{decode, encode};
use pocketcloud_crypto::field::{Field, Mersenne61};
use pocketcloud_crypto::sharing::{reconstruct_vector, verify_mac};

mod mini_json;
use mini_json::Json;

fn load() -> Json {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../qa/golden/crypto/vectors.json"
    );
    let text = std::fs::read_to_string(path).expect("read golden vectors");
    Json::parse(&text)
}

fn fe(s: &str) -> Mersenne61 {
    Mersenne61::from_decimal(s).expect("canonical field element")
}

#[test]
fn field_ops_match_poc() {
    let v = load();
    let ops = v.get("fieldOps").arr();
    assert!(ops.len() >= 81, "expected the full field-op grid");
    for op in ops {
        let a = fe(op.get("a").str());
        let b = fe(op.get("b").str());
        assert_eq!(a.add(b).to_decimal(), op.get("add").str(), "add mismatch");
        assert_eq!(a.sub(b).to_decimal(), op.get("sub").str(), "sub mismatch");
        assert_eq!(a.mul(b).to_decimal(), op.get("mul").str(), "mul mismatch");
    }
}

#[test]
fn encodings_match_poc() {
    let v = load();
    for e in v.get("encodings").arr() {
        let x = e.get("x").num();
        let enc: Mersenne61 = encode(x);
        assert_eq!(enc.to_decimal(), e.get("encoded").str(), "encode {x}");
        let dec = decode(&enc, 1);
        assert!((dec - e.get("decoded1").num()).abs() < 1e-9, "decode {x}");
    }
    for p in v.get("products").arr() {
        let x: Mersenne61 = encode(p.get("x").num());
        let y: Mersenne61 = encode(p.get("y").num());
        assert_eq!(
            x.mul(y).to_decimal(),
            p.get("encProduct").str(),
            "enc product"
        );
        assert!((decode(&x.mul(y), 2) - p.get("decoded2").num()).abs() < 1e-6);
    }
}

#[test]
fn reconstruction_matches_poc() {
    let v = load();
    for set in v.get("shareSets").arr() {
        let shares: Vec<Vec<Mersenne61>> = set
            .get("shares")
            .arr()
            .iter()
            .map(|row| row.arr().iter().map(|s| fe(s.str())).collect())
            .collect();
        let recon = reconstruct_vector(&shares);
        let expected: Vec<String> = set
            .get("reconstructed")
            .arr()
            .iter()
            .map(|s| s.str().to_string())
            .collect();
        let got: Vec<String> = recon.iter().map(|x| x.to_decimal()).collect();
        assert_eq!(got, expected, "reconstruction mismatch");
    }
}

#[test]
fn mac_relation_matches_poc() {
    let v = load();
    let mc = v.get("macCases");
    let alpha = fe(mc.get("alpha").str());
    let val: Vec<Mersenne61> = mc
        .get("reconstructedValue")
        .arr()
        .iter()
        .map(|s| fe(s.str()))
        .collect();
    let mac: Vec<Mersenne61> = mc
        .get("reconstructedMac")
        .arr()
        .iter()
        .map(|s| fe(s.str()))
        .collect();
    assert!(verify_mac(&val, &mac, alpha), "honest MAC must verify");
    assert_eq!(
        verify_mac(&val, &mac, alpha),
        mc.get("honestVerifies").boolean()
    );

    // Tamper element 0 by +1 — must fail, matching the PoC's tamperedVerifies.
    let mut tampered = val.clone();
    tampered[0] = tampered[0].add(Mersenne61::one());
    assert!(
        !verify_mac(&tampered, &mac, alpha),
        "tampered MAC must fail"
    );
    assert_eq!(
        verify_mac(&tampered, &mac, alpha),
        mc.get("tamperedVerifies").boolean()
    );
}

#[test]
fn matvec_matches_poc() {
    let v = load();
    let mv = v.get("matvec");
    let matrix: Vec<Vec<Mersenne61>> = mv
        .get("matrix")
        .arr()
        .iter()
        .map(|row| row.arr().iter().map(|s| fe(s.str())).collect())
        .collect();
    let xshare: Vec<Mersenne61> = mv.get("xShare").arr().iter().map(|s| fe(s.str())).collect();
    let yshare: Vec<String> = matrix
        .iter()
        .map(|row| {
            row.iter()
                .zip(&xshare)
                .fold(Mersenne61::zero(), |acc, (w, x)| acc.add(w.mul(*x)))
                .to_decimal()
        })
        .collect();
    let expected: Vec<String> = mv
        .get("yShare")
        .arr()
        .iter()
        .map(|s| s.str().to_string())
        .collect();
    assert_eq!(yshare, expected, "matvec share result must match PoC");
}
